clear; clc; close all;

% Cross model simulation -- v2
% Uses V4 fitted parameters (physical etainf >= 0.001 Pa.s) and Vp = 10 mm/s.
% Calls bioprinting_algorithm_cross_v2 (bracketed fzero, entrance-loss notes).
% Parâmetros baseados no modelo Cross (Viscosity-domain fits)
% Ramp 1: v4 - log-space OLS
% Unsheared samples
samples = struct(...
    'Name',   {'C15', 'C15 Gira 5.5', 'Bozzano''s Hair Gel'}, ...
    'eta0',   {578.26, 2439.5, 6354.55}, ...
    'etainf', {0.0162966, 0.001, 0.932091}, ...
    'lambda', {3.71132, 4.09905, 73.0454}, ...
    'm',      {0.810869, 0.987578, 0.865734}, ...
    'Vp',     0.025, ... % <--- Scalar expansion applies this to all
    'rho',    {898, 898, 885} ...
);

% Ramp 2: v4 - log-space OLS
samples_sheared = struct(...
    'Name',   {'C15', 'C15 Gira 5.5', 'Bozzano''s Hair Gel'}, ...
    'eta0',   {254.259, 951.474, 57503.1}, ...
    'etainf', {0.001, 0.001, 0.816576}, ...
    'lambda', {3.91943, 7.96028, 1544.3}, ...
    'm',      {0.81443, 0.854576, 0.825573}, ...
    'Vp',     0.003, ... % <--- Scalar expansion applies this to all
    'rho',    {898, 898, 885} ...
);

% --- Syringe & needle geometry (21G, BD 10 mL syringe) ---
Rs = 14.3e-3 / 2;       % Syringe radius (m) = 7.15 mm
Rn = 0.000515 / 2;      % 21G needle radius (m) = 0.2575 mm
Ln = 1.25 * 0.0254;     % Needle length (m) = 31.75 mm
Ls = 90e-3;             % Syringe length (m)

orientation   = 'downward';
output_folder = fullfile(pwd, 'Cross-Vp3-Sheared');

if ~exist(output_folder, 'dir')
    mkdir(output_folder);
end

results_all = cell(numel(samples_sheared), 1);

for i = 1:numel(samples_sheared)
    s = samples_sheared(i);
    results = bioprinting_algorithm_cross_v2( ...
        Rs, Rn, Rn, Ln, Ls, s.Vp, s.eta0, s.etainf, s.lambda, s.m, s.rho, ...
        'Name',              s.Name, ...
        'PlotResults',       true, ...
        'SaveData',          true, ...
        'SaveFigures',       true, ...
        'Orientation',       orientation, ...
        'OutputFolder',      output_folder, ...
        'IncludeHydrostatic', true);
    results_all{i} = results;
end

create_multi_sample_plots(results_all, output_folder, orientation);

function create_multi_sample_plots(results_all, output_folder, orientation)
    colors = lines(numel(results_all));
    f = figure('Position', [100, 100, 1200, 400]);

    subplot(1, 2, 1); hold on;
    for i = 1:numel(results_all)
        plot(results_all{i}.profiles.r_needle * 1000, ...
             results_all{i}.profiles.u_needle * 1000, ...
             'LineWidth', 2, 'Color', colors(i,:), ...
             'DisplayName', results_all{i}.sample_name);
    end
    xlabel('Radial Position (mm)'); ylabel('Velocity (mm/s)');
    title('Needle Velocity Profiles'); legend('show'); grid on;

    subplot(1, 2, 2); hold on;
    for i = 1:numel(results_all)
        plot(results_all{i}.profiles.r_syringe * 1000, ...
             results_all{i}.profiles.u_syringe * 1000, ...
             'LineWidth', 2, 'Color', colors(i,:), ...
             'DisplayName', results_all{i}.sample_name);
    end
    xlabel('Radial Position (mm)'); ylabel('Velocity (mm/s)');
    title('Syringe Velocity Profiles'); legend('show'); grid on;
    sgtitle(sprintf('Velocity Profiles', orientation));

    filename = fullfile(output_folder, ...
        sprintf('all_samples_velocity_%s_%s.png', orientation, datestr(now, 'yyyymmdd_HHMMSS')));
    exportgraphics(f, filename, 'Resolution', 1200);
    disp(['Figure saved as: ', filename]);
end
